### PR TITLE
Give profiles locations #39

### PR DESCRIPTION
**Pull request by David-Egan**

### CODE REVIEW

**Comment by aaron13michael** [comment]
Have you tested that you can create a user with and without a location?

**Comment by David-Egan** [comment]
Should location be optional when creating users?  I assumed they would be required.  I did test creating a user with and without a location and as expected with succeeded while without failed.  Let me know if you think it should be optional and I can make the appropriate change.

**Comment by aaron13michael** [comment]
It should be optional. For normal users we will always be using the latitude and longitude from their current location, but premium users can use a different location.

**Comment by David-Egan** [comment]
That makes a lot of sense I can make that change late tonight or tomorrow or if you'd like it should be as simple as adding null = True, blank = True to location in Profile.  I would do it straight from Github but I'd rather test it before merging.

**Pull request merged**
